FROM mcr.microsoft.com/devcontainers/python:3.13

RUN apt update && apt install -y \
  libwebkit2gtk-4.1-dev \
  build-essential \
  curl \
  wget \
  file \
  libxdo-dev \
  libssl-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev \
  imagemagick \
  cmake \
  xdg-utils